version: "3.8"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:4.0-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # RabbitMQ instance
      - 5672:5672
      # Web Interface
      - 15672:15672
